name: Release - Package app

# Controls when the workflow will run
on:
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate SHA256 and PACKAGE_SOURCE
        working-directory: src
        run: |
          zip ../bir.node-${{github.ref_name}}.zip -r *
  
      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{github.ref}}
          file: bir.node-${{github.ref_name}}.zip
  
      - name: Generate SHA256 and PACKAGE_SOURCE
        run: |
          export SHA256=$(sha256sum bir.node-${{github.ref_name}}.zip)
          echo "::set-env name=SHA256::$SHA256"
          export PACKAGE_SOURCE=https://github.com/apps-alis-is/bir.node/releases/download/${{github.ref_name}}/bir.node-${{github.ref_name}}.zip
          echo "::set-env name=SHA256::$SHA256"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: alis-is/air
          event-type: app-release
          client-payload: '{ "repository": "${{github.repository}}", "version": "${{github.ref_name}}", "package": "$PACKAGE_SOURCE", "sha256": "$SHA256"}'
        
          
          
